name: GitHub Actions Build and Deploy Demo
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@main
    - name: Setup Node
      uses: actions/setup-node@v1
      with:
        node-version: '16.17.0'
    - name: Install Dependencies
      run: npm install -g pnpm && pnpm install && pnpm build
    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3
      with:
        target_branch: gh-pages
        build_dir: build
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
